env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - standard-with-typescript
  - "eslint:recommended"
  - "@vue/typescript/recommended"
overrides:
  - files: ["*.vue"]
ignorePatterns: [dist/, nuxt.config.ts, unocss.config.ts]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  {
    "vue/multi-word-component-names": "off",
    "no-undef": "off",
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": "off",
    "@typescript-eslint/consistent-type-imports": "warn"
  }
