name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm run lint
