name: Github pages
on:
  push:
      paths:
          - 'docs/**'
          - 'README.md'
      branches:
          - 'master'
env:
  CI: false
jobs:
  gh-page-publish:
    runs-on: [self-hosted, Linux]
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build doc
        run: |
            pnpm install
            pnpm run build
      - name: Doxygen html for github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
